### ISSUE TITLE
Idea why Clair3 doesn't call this SNP

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#208] opened 2023-07-16 11:57 UTC
Hello,

comparing bcftools mpileup and Clair3

Clair3 is generally much more able, especially in high heterozygosity region, but sometimes not. On the following pic, any idea why neither the pileup (pileup.vcf.gz), nor the neural network (merge_output.vcf.gz) call a bi-allelic SNP there? 

the D5C1.sorted is an illumina read alignment
the barcode02 is the ONT alignment
Of course, same biological clonal population

The whole ONT alignment is shown. I can't show the whole illumina alignment (too many reads). 

![igv_snapshot_CLAIR3_missing_a_snp](https://github.com/HKU-BAL/Clair3/assets/81575666/858231d3-f845-42ff-ba15-40951741e5be)

The variant is the one called No Variants Found at the line cmair3_only.vcf.gz

Any idea? 

EDIT: remove a clearly false sentence, apologizes

**Comment by Axze-rgb** [comment] 2023-07-16 13:01
Yes, here it is, the region is 10⁶ to 2.10⁶ here is the link
[link](https://we.tl/t-2ua8JMAtsA)

**Comment by Axze-rgb** [comment] 2023-07-17 08:07
Hello, if you wish, I can share with you the whole bam, by the way, don't hesitate to come back to me

**Comment by zhengzhenxian** [comment] 2023-07-17 14:17
Hi @Axze-rgb, 

Thank you for sharing the data with us. We observed that the heterozygous "variants" clustered within the flanking 20 base pairs. The occurrence of these variants simultaneously in either of the haplotypes in a small region suggests that they might be sequencing errors caused by alignment artifacts. 

As a result, you might find that Clair3 has called all of these variants as "RefCall". In addition, we have observed a 6-base pair deletion in the same position in the Illumina data. We are curious about how you were able to determine that the Illumina data supports a T/C alteration at this position. Could you please provide more information or clarification on this?

Zhenxian

**Comment by Axze-rgb** [comment] 2023-07-17 14:43
Hello, 

Clair3 gave a "PASS" to all those variants if I understand your argument, it didn't identify them as RefCall. Actually, there is no refCall at all in the vcf.

```Chrom_3	1591122	.	T	A	13.65	PASS	F	GT:GQ:DP:AF	0/1:13:13:0.3846
Chrom_3	1591124	.	A	T	10.80	PASS	F	GT:GQ:DP:AF	0/1:10:13:0.3846
Chrom_3	1591125	.	C	T	12.89	PASS	F	GT:GQ:DP:AF	0/1:12:13:0.3846
zcat merge_output.vcf.gz|grep "1591122" -C 4
Chrom_3	1591041	.	A	C	25.86	PASS	P	GT:GQ:DP:AF	0/1:25:13:0.5385
Chrom_3	1591107	.	A	G	21.14	PASS	F	GT:GQ:DP:AF	0/1:21:13:0.4615
Chrom_3	1591116	.	C	T	9.70	PASS	F	GT:GQ:DP:AF	0/1:9:13:0.3846
Chrom_3	1591117	.	A	C	10.77	PASS	F	GT:GQ:DP:AF	0/1:10:13:0.3846
**Chrom_3	1591122	.	T	A	13.65	PASS	F	GT:GQ:DP:AF	0/1:13:13:0.3846
Chrom_3	1591124	.	A	T	10.80	PASS	F	GT:GQ:DP:AF	0/1:10:13:0.3846
Chrom_3	1591125	.	C	T	12.89	PASS	F	GT:GQ:DP:AF	0/1:12:13:0.3846**
Chrom_3	1591126	.	A	C	12.27	PASS	F	GT:GQ:DP:AF	0/1:12:13:0.3846
Chrom_3	1591127	.	A	G	16.71	PASS	F	GT:GQ:DP:AF	0/1:16:13:0.4615
```

Regarding the illumina data, it does NOT support the T/C, I am sorry, no idea why I wrote that sentence. Again, extremely sorry. 

So, no the illumina doesn't support a T/C. However, the T/C is supported by bcftools on the ONT reads. 

So, if I understand you correctly, you were expecting that such cluster of SNP is artefactual and that Clair3 should have given them the RefCall value. But it gives a PASS value, see bold above. 

Any idea? 

Please, note that it IS possible this is a real biological pattern in the genome. This is not the human genome. 

For clarity I edited the very first message to remove the sentence about the illumina reads.

**Comment by aquaskyline** [comment] 2023-07-18 03:21
@Axze-rgb ”So, no the illumina doesn't support a T/C. However, the T/C is supported by bcftools on the ONT reads.“ Am I correct that T/C at ...120bp is not supported by Illumina reads, which means that T/C is not necessarily a truth? We found no C allele at the position in the Illumina alignments, although you mentioned you showed only a part of all Illumina alignments. Notice that bcftools is not as sophisticated as Clair3 in calling small variants in ONT long-reads. bcftools is using a Bayesian model that basically, the higher the AF, the more likely a variant is called. But high AF in ONT doesn't necessarily mean a true variant.

**Comment by aquaskyline** [comment] 2023-07-18 03:35
Re "So, if I understand you correctly, you were expecting that such cluster of SNP is artefactual and that Clair3 should have given them the RefCall value. But it gives a PASS value, see bold above."

Not necessarily. A cluster of small variants leads to lower variant qualities of all variants in the cluster. A cluster of small variants can result from alignment artifacts, but can also be true. True variants are usually with strong support that, even being penalized for being in a cluster, are still with good variant quality, thus being marked as 'PASS'.

**Closed** 2023-07-25 20:16 UTC
