### ISSUE TITLE
Clair3 does not call all positions with --vcf_fn

### ISSUE THREAD

**Issue by david-roquis** [HKU-BAL/Clair3#156] opened 2022-12-02 12:14 UTC
Hello!

I am using Clair3 to call SNPs from Nanopore reads on different samples and have a call for all positions detected in each samples. To do so, I ran Clair3 once on all samples, made a multivcf with all positions from all samples, and rerun Clair3 again with --vcf_fn=mypositions.vcf --print_ref_calls --include_all_ctgs. 

My datasets are small (220 contigs covering 3 Mo bp) so it is quite fast. However, many positions present in the vcf I supply with --vcf_fn are not called in the samples (ex: 24 000 positions, only 9000 calls in some samples). I do have some positions properly calls with "refcall" in the vcf, but many are missing. What could be the cause of this? I have a min average coverage of 10X for all samples on all these contigs.

Sincerely

David

**Comment by zhengzhenxian** [comment] 2022-12-04 08:17
Hi David,

The missing variants are probably because they failed to meet `--min_coverage(4)`, `--snp_min_af(0.08)`, and `--indel_min_af(0.15)` in some specific samples.

We updated the force calling logic to output all genotyped records in the GitHub repository. Please clone the repo and overwrite the following files.
```
CLAIR3_PATH=${CONDA_PREFIX}/bin
git clone https://github.com/HKU-BAL/Clair3.git
cd Clair3
mkdir -p ${CLAIR3_PATH}/postprocess
cp -r clair3.py ${CLAIR3_PATH}/
cp -r postprocess/AddBackMissingVariantsInGenotyping.py ${CLAIR3_PATH}/postprocess/
cp -r postprocess/__init__.py ${CLAIR3_PATH}/postprocess/
cp -r scripts/clair3_c_impl.sh ${CLAIR3_PATH}/scripts/
cp -r scripts/clair3.sh ${CLAIR3_PATH}/scripts/ `
```

The update will be included in the next release (v0.1-r13).

**Comment by david-roquis** [comment] 2022-12-06 09:24
Hello!

Thanks for your answer! Unfortunately, I have technical issues to implement the changes you suggest. I run Clair3 on my Intel Mac through Docker, as I have never been able to install Clair3 through conda. I get the following error:

>conda create -n clair3 -c bioconda clair3 python=3.9.0 -y
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
clair3 -> python=3.6.10
clair3 -> numpy=1.19.5 -> python[version='>=3.10,<3.11.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
python=3.9.0

 Is there any way to manually modify the files in the Docker container the same way you suggest as with Conda? Thanks a lot

**Comment by david-roquis** [comment] 2022-12-06 10:44
Hello again! 

Finally, I rebuilt the docker container using the latest changes on the git repository. The tool works, but now I don't have any reference calls at all anymore. It seems `--vcf_fn=mypositions.vcf.gz --print_ref_calls` are not taken into account anymore (I get the same results with or without them).

**Comment by david-roquis** [comment] 2022-12-06 12:40
Hello again!

I managed to built a new docker container based on the last github version of Clair3. It now generates a vcf file with all positions listed in the reference vcf file when using `--vcf_fn=mypositions.vcf --print_ref_calls --include_all_ctgs`, but there is something really strange happening. For some reference positions (where my sample is not different from the reference allele), I do have a normal SNP calling as such:

STRG.1.1	484	.	T	.	15.99	RefCall	P	GT:GQ:DP:AF	0/0:15:46:0.8696

However for the vast majority of the positions with no differences, the line do appear in the VCF, but rather than having a "refcall", it is empty and it copy-paste the value of the reference sample in the reference VCF, as such. This is really misleading because it does not correspond to the call on my current sample, but rather the call of another sample in the file I used with --vcf_fn. Is this normal? Example from the merge_output.vcf file where the info in the sample column is NOT from the treated sample, but a copy of the info from the reference VCF file. 

STRG.1.1	77	.	G	.	3.47	.	F	GT:GQ:DP:AF	./.:3:2:0.5

I visually inspected some of these positions in IGV, and I don't see any ambiguity in the reads (all of them have the homozygous reference nucleotide) with most of the time coverage >10 reads. Any ideas?

Thanks!

**Comment by zhengzhenxian** [comment] 2022-12-06 13:42
Hi David,

We confirmed it a bug only in genotyping mode, and we will fix it in 1-2 days. Thanks so much for your reporting!

Zhenxian

**Comment by david-roquis** [comment] 2022-12-06 15:06
Hi Zhenxian,

Thanks for the follow up! Please keep me in touch for the patch!

Sincerely

David

**Comment by zhengzhenxian** [comment] 2022-12-07 13:52
Hi David,

We have fixed the bug, and pls re-pull the latest docker image or use the updated code to rebuild your container.  Now, for every variant that failed in genotyping, we set the `ALT`, `QUAL`, and `FILTER` to ".",  and only keep `GT` tag for `INFO` column in the output VCF. 

If you wish to force outputting VCF INFOs (DP, AF, etc.) from the called sample, I would suggest you add `--snp_min_af=0.0` and `--indel_min_af=0.0` parameters.  However, for those variants with coverage < 2, we still cannot make genotyping as we cannot make tensor for them; the compensation logic above will still work.

Please let me know if you have any questions!

**Comment by david-roquis** [comment] 2022-12-08 11:27
Hi Zhenxian,

It works perfectly! Thanks a lot!

Sincerely

David

**Comment by jts** [comment] 2022-12-08 17:35
I had the same issue as @david-roquis so used the latest version of the code but I receive an error at the end of the process:

```
[INFO] Double check re-genotyping variants
Traceback (most recent call last):
  File "/opt/bin/scripts/../clair3.py", line 105, in <module>
    main()
  File "/opt/bin/scripts/../clair3.py", line 99, in main
    submodule.main()
  File "/opt/bin/postprocess/AddBackMissingVariantsInGenotyping.py", line 181, in main
    genotype_vcf(args)
  File "/opt/bin/postprocess/AddBackMissingVariantsInGenotyping.py", line 137, in genotype_vcf
    gt_index = info_column.split(':').index("GT")
ValueError: 'GT' is not in list
```

I believe this is because my `vcf_fn` does not contain genotypes.

**Comment by aquaskyline** [comment] 2022-12-08 23:41
Fixing.

**Comment by jts** [comment] 2022-12-08 23:51
Sure, it looks like this:

```
chr1    3951025 rs12726656      C       A       889196  PASS    AC=2974;AF=0.073
```

It is from the gnomad AF-only sites VCF.

Jared

**Comment by zhengzhenxian** [comment] 2022-12-09 02:39
Hi @jts,

Bug fixed, and pls re-pull the latest docker image. Please let me know if the issue persists, thanks!

Zhenxian

**Comment by jts** [comment] 2022-12-09 13:31
Will do, thanks!

**Comment by jts** [comment] 2022-12-09 16:33
The latest version ran to completion with this VCF, thanks for the quick fix.

**Closed** 2023-01-02 23:50 UTC
